version: "3.9"

services: 
  # Microservizio di registrazione
  registration_ms:
    build:
      context: .
      dockerfile: ./dockerfiles/registration/Dockerfile
    environment: 
      - REG_PORT
      - SIZE
      - VERBOSE
      - SEQ_HOSTNAME
    volumes:
      - ./logs:/logs

  # Microservizio sequencer
  sequencer_ms:
    build:
      context: .
      dockerfile: ./dockerfiles/sequencer/Dockerfile
    environment:
      - CHAT_PORT
      - REG_PORT
      - VERBOSE
      - SIZE
    volumes:
      - ./logs:/logs

  # Microservizio peer
  peer_ms:
    build:
      context: .
      dockerfile: ./dockerfiles/peer/Dockerfile
    ports:
      - $WS_PORT
    environment: 
      - WS_PORT
      - REG_PORT
      - CHAT_PORT
      - SIZE
      - REG_HOSTNAME
      - SEQ_HOSTNAME
      - REDIS_HOSTNAME
      - VERBOSE
    scale: $SIZE
    depends_on: 
      - "peer_ds"
    volumes:
      - ./peer/webserver/assets:/assets:ro
      - ./logs:/logs

  peer_ds:
    image: "redis:alpine"