version: "3.9"
services: 
  redis:
    image: "redis:alpine"
  registration_ms:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.server
    environment: 
      - SIZE
    ports:
      - "2929:2929"
    depends_on: 
      - "redis"
  client_1:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.client
    environment: 
      - COMUNIGO_RHOST
  client_2:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.client
    environment: 
      - COMUNIGO_RHOST
  client_3:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.client
    environment: 
      - COMUNIGO_RHOST
    
