version: "3.9"
services: 
  registration_ds:
    image: "redis:alpine"
  registration_ms:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.server
    environment: 
      - REG_PORT
      - SIZE
      - VERBOSE
    depends_on: 
      - "registration_ds"
  peer:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.peer
    ports:
      - $WS_PORT
    environment: 
      - WS_PORT
      - REG_PORT
      - REG_HOSTNAME
      - SIZE
      - VERBOSE
      - TOS
    scale: $SIZE
