FROM golang:1.16-alpine AS build
ENV GO111MODULE=on GOOS=linux GOARCH=amd64
WORKDIR /registration-ms
COPY . .
RUN go mod download && go build -o client ./client/client.go

FROM alpine:latest  
ARG user
ENV COMUNIGO_USER=$user
WORKDIR /registration-ms
COPY --from=build /registration-ms/client/client .
ENTRYPOINT ./client -u $COMUNIGO_USER